/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
<<<<<<< HEAD
 * Generated by convex@1.14.0.
=======
>>>>>>> 46f376e (rebased to use different starter code)
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as init from "../init.js";
import type * as messages from "../messages.js";
<<<<<<< HEAD
=======
import type * as openai from "../openai.js";
>>>>>>> 46f376e (rebased to use different starter code)

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  init: typeof init;
  messages: typeof messages;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
